import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { recentlyViewed } from "@/utils/mock";
import { CardsCarousel } from "@/components/CardsCarousel/CardsCarousel";
import { MenuItem } from "@/components/MenuItem/MenuItem";
import { SearchBarMain } from "@/components/SearchBarMain/SearchBarMain";
import {
  useAppDispatch,
  useAppSelector,
} from "@/store/hooks";
import { useEffect } from "react";
import { getUsersListAction } from "@/store/users/action";
import { useRouter } from "next/router";
import { MainLayout } from "@/components/layouts/main";
import { getRestarauntsList } from "@/store/restaraunts/api";
import { getRestarauntsListAction } from "@/store/restaraunts/action";

export default function Home() {
  const router = useRouter();
  const { restaraunts, status } = useAppSelector(
    (state) => state.restaraunts
  );
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(getRestarauntsListAction());
  }, []);
  return status === "loading" ? (
    <h1>LOADING....</h1>
  ) : (
    <>
      <Head>
        <title>Halal Guide</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <MainLayout>
        <section className={"section"}>
          <div className={styles.searchContainerBro}>
            <SearchBarMain />
          </div>
        </section>
          <section className="section">
            <CardsCarousel
              size="md"
              title="Recently Viewed"
              items={restaraunts}
            />
          </section>
        <section className="section">
          <CardsCarousel
            size="md"
            title="Most Loved"
            items={restaraunts}
          />
        </section>
        <section className="section">
          <CardsCarousel
            size="md"
            title="You might like this"
            items={restaraunts}
          />
        </section>
      </MainLayout>
    </>
  );
}
